export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_CLEAR = 'AUTH_CLEAR'

export const LOCAL_UPDATE = 'LOCAL_UPDATE'
export const REMOTE_WATCH = 'REMOTE_WATCH'
export const REMOTE_QUERY = ''

// export const allRemotes = [REMOTE_WATCH]

// export default {
//   AUTH_START: 'AUTH_START',
//   AUTH_SUCCESS: 'AUTH_SUCCESS',
//   AUTH_CLEAR: 'AUTH_CLEAR',
//   LOCAL_UPDATE: 'LOCAL_UPDATE',
//   LOCAL_REMOVE: 'LOCAL_REMOVE',
//   REMOTE_WATCH: 'REMOTE_WATCH',
//   REMOTE_QUERY: 'REMOTE_QUERY',
//   REMOTE_PUSH: 'REMOTE_PUSH',
//   REMOTE_UPDATE: 'REMOTE_UPDATE',
//   REMOTE_SET: 'REMOTE_SET',
//   REMOTE_REMOVE: 'REMOTE_REMOTE'
// }